{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-db
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: delivery-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-db
  template:
    metadata:
      labels:
        app: delivery-db
    spec:
      containers:
        - name: delivery-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "{{ $.Values.global.postgresql.auth.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ $.Values.global.postgresql.auth.password }}"
            - name: POSTGRES_DB
              value: "{{ index .Values.databases 0 }}"
          volumeMounts:
            - name: delivery-db-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "{{ $.Values.global.postgresql.auth.username }}"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "{{ $.Values.global.postgresql.auth.username }}"
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: delivery-db-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: delivery-db-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
{{ end }}

{{- if and .Values.enabled .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delivery-db-pvc
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: delivery-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }} 