{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: delivery-db-postgresql
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: delivery-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app: delivery-db
{{ end }} 