{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: payment-db-postgresql
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: payment-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app: payment-db
{{ end }} 