{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: smtp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: http-ui
              containerPort: {{ .Values.service.uiPort }}
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: http-ui
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: http-ui
            initialDelaySeconds: 5
            periodSeconds: 2
{{ end }} 