{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: mailhog
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: {{ .Values.service.uiPort }}
      targetPort: http-ui
      protocol: TCP
      name: http-ui
  selector:
    app: mailhog
{{ end }} 