{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: delivery-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: delivery-service
{{ end }} 