{{ if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: rabbitmq
type: Opaque
data:
  username: {{ $.Values.global.rabbitmq.auth.username | b64enc }}
  password: {{ $.Values.global.rabbitmq.auth.password | b64enc }}
{{ end }} 